config/routes.rb
Rails.application.routes.draw do

  root 'shared#home'

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
  }

  resources :posts

  get '/blogger/:id', to: 'blogger#show', as: 'blogger'
  get '/like/:id', to: 'posts#like', as: 'like'

  post '/posts/:id/comment', to: 'comments#create', as: 'comments'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  def user
    User.find(self.user_id)
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  def user_name
    user = User.find(self.user_id)
    "#{user.first_name} #{user.last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :bio
  validates_uniqueness_of :email

  has_many :posts
  has_many :comments

  def user_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogger_controller.rb
class BloggerController < ApplicationController
  def show
    @blogger = User.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:id])
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = 'Comment Saved Successfully!'
      redirect_to post_path(@post)
    else
      flash[:alert] = 'Comment Was Not Saved!'
      redirect_to post_path(@post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:like, :new, :edit, :destroy, :update]

  def like
    @post = Post.find(params[:id])
    @post.likes += 1
    @post.save
    redirect_to :back
  end

  def show
    @post = Post.find(params[:id])
    @blogger = User.find(@post.user_id)
    @new_comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = 'Post Created Successfully!'
      redirect_to root_path
    else
      flash[:alert] = 'Post Was Not Saved!'
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = 'Post Updated Successfully!'
      redirect_to root_path
    else
      flash[:alert] = 'Post Was Not Saved!'
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = 'Post "#{@post.title}" Has Been Deleted!'
      redirect_to root_path
    else
      flash[:alert] = 'Post Was Not Deleted!'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController
  def home
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
 before_action :configure_sign_up_params, only: [:create]
 before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :bio])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :bio])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogger_helper.rb
module BloggerHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/views/blogger/show.html.erb
<div class='center col-md-6 col-md-offset-3' style='margin-top:10px;margin-bottom:10px;'>
  <h2><%= @blogger.first_name %> <%= @blogger.last_name %></h2>
  <p><%= @blogger.bio %></p>
</div>

<div class='col-md-8 col-md-offset-2'>
  <% @blogger.posts.each do |post| %>
    <div class='post col-md-12'>
      <h3><%= post.title %></h3>
      <p><%= post.body %></h3>
      <p style='float:right;'>&nbsp;<%= post.likes %></p> 
      <a href="/like/<%= post.id %>" style='float:right;'><i class='fa fa-heart'></i></a>
    </div>
  <% end %>
</div>

<div class='center col-md-6 col-md-offset-3'>
  <h3>Comments</h3>
  <% if current_user %>

  <% else %>
    <%= link_to 'Login To Comment', new_user_session_path, class: 'center' %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<div class='new-post center col-md-6 col-md-offset-3'>
  <h3>Edit Comment</h3>
  <%= form_for @comment do |f| %>
    <%= f.text_area :body, autofocus: true, placeholder: 'Body', class: 'body'%>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/_main_banner.html.erb
<div class='main-banner center col-md-8 col-md-offset-2'>
  <h4>Read. Write. Learn.</h4>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <div class="center flash-messages" id="flash"><%= value %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Write', new_post_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to 'My Page', blogger_path(current_user) %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %><l1>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render('layouts/navbar') %>
    <%= render('layouts/messages') %>
    <%= render('layouts/main_banner') %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class='new-post center col-md-6 col-md-offset-3'>
  <h3>Write</h3>
  <%= form_for @post do |f| %>
    <%= f.text_area :title, autofocus: true, placeholder: 'Title', class: 'title' %>
    <%= f.text_area :body, placeholder: 'Body', class: 'body'%>
    <%= f.submit %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render('form') %>

app/views/posts/new.html.erb
<%= render('form') %>

app/views/posts/show.html.erb
<div class='center col-md-6 col-md-offset-3' style='margin-top:10px;margin-bottom:10px;'>
  <h2><%= @post.user_name %></h2>
  <p><%= @blogger.bio %></p>
  <% if user_signed_in? %>
    <% if @post.user_id == current_user.id %>
      <%= link_to 'Edit Post', edit_post_path(@post) %>&nbsp;
      <%= link_to 'Delete Post', post_path(@post), method: :delete, class: 'danger', data: {confirm: 'Delete This Post?!'} %>
    <% end %>
  <% end %>
</div>

<div class='post-show col-md-8 col-md-offset-2'>
  <h3><%= @post.title %></h3>
  <p><%= @post.body %></h3>
  <p style='float:right'>&nbsp;<%= @post.likes %></p>
  <a href="/like/<%= @post.id %>" style='float:right;'><i class='fa fa-heart'></i></a>
</div>

<div class='col-md-8 col-md-offset-2'>
  <h3 class='center'>Comments</h3>
  <div class='post col-md-12'>
    <% @post.comments.each do |comment| %>
      <div class='post-comments'
        <h5><%= link_to comment.user.user_name, blogger_path(comment.user.id) %><h5>
        <p><%= comment.body %><p>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div id='new-comment' class='hidden'>
      <%= form_for @new_comment do |f| %>
        <%= f.text_area :body, autofocus: true, placeholder: 'New Comment', class: 'body'%>
        <%= f.hidden_field :post_id, value: @post.id %>
        <%= f.submit %>
      <% end %>
    </div>
    <input type='submit' id='show-new-comment' value='New Comment'/>
  <% else %>
    <%= link_to 'Login To Comment', new_user_session_path, class: 'center' %>
  <% end %>
</div>

app/views/shared/home.html.erb
<div class='col-md-6 col-md-offset-3'>
  <% @posts.each do |post| %>
    <div class='post col-md-12'>
      <h5 class='post-user'><%= link_to post.user_name, blogger_path(post.user_id) %></h5>
      <h3><%= link_to post.title, post_path(post) %></h3>
      <P><%= truncate(post.body, length: 100) %></p>
      <p style='float:right;'>&nbsp;<%= post.likes %></p>
      <a href="/like/<%= post.id %>" style='float:right;'><i class='fa fa-heart'></i></a>
    </div>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>